# Generated by Django 4.1.2 on 2022-10-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registr_date',
            new_name='register_date',
        ),
    ]
